def direction_control_move():
    Tinybit.car_ctrl(Tinybit.CarState.CAR_RUN)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_BACK)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_LEFT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_RIGHT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_SPINLEFT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_SPINRIGHT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_STOP)
    basic.pause(1000)
basic.forever(direction_control_move)
